import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateGamesTable1707747966979 implements MigrationInterface {
  private gamesTableName = 'games';
  private gameStatusEnumName = 'game_status';
  public async up(queryRunner: QueryRunner): Promise<void> {
    const createGameStatusQuery = `
    CREATE TYPE "${this.gameStatusEnumName}" AS ENUM (
      'ACTIVE',
      'DRAW',
      'FINISHED'
    );
    `;

    await queryRunner.query(createGameStatusQuery);

    const createTableQuery = `
    CREATE TABLE "${this.gamesTableName}" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "status" ${this.gameStatusEnumName} NOT NULL,
      "info" varchar,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    `;
    await queryRunner.query(createTableQuery);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable(this.gamesTableName);
    await queryRunner.query(`DROP TYPE ${this.gameStatusEnumName}`);
  }
}
