version: "3"

includes:
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
    aliases:
      - s

  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client
    aliases:
      - c

tasks:
  init:
    cmds:
      - task: client:init
      - task: server:init
    desc: Initialize the client and server by installing dependencies
