version: '3.8'
services:
  app:
      container_name: gameofthree-app
      init: true
      build:
          context: ./
          target: development
      volumes:
          - ./:/app
          - /app/node_modules
      ports:
          - 3000:3000
      depends_on:
        postgres:
          condition: service_healthy

  postgres:
    image: postgres:16.1
    container_name: gameofthree-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gameofthree
      POSTGRES_USER: gameofthree
      POSTGRES_PASSWORD: gameofthree
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres: