version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: test-gameofthree-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: test-gameofthree
      POSTGRES_USER: test-gameofthree
      POSTGRES_PASSWORD: test-gameofthree
    networks:
        - test-gameofthree-network

  redis:
      image: redis:7.2
      container_name: test-gameofthree-redis
      ports:
          - 6380:6379
      networks:
        - test-gameofthree-network
networks:
   test-gameofthree-network: